### ISSUE TITLE
Choosing which title will be searched

### ISSUE THREAD

**Issue by toprak** [Metacor/nyaa-linker#3]
### Proposal

it doesn't make sense to me to search for the Romaji and the English translation of an anime title at the same time, because usually most anime releasers only use the Romaji, which can cause the user to miss a good release.
Results of _"Watashi no Shiawase na Kekkon"|"My Happy Marriage"_ query
![image](https://github.com/Metacor/nyaa-linker/assets/43301560/c9580b4c-c3d8-4b06-9ffa-e994ee03cae8)
Results of _"Watashi no Shiawase na Kekkon"_ query
![image](https://github.com/Metacor/nyaa-linker/assets/43301560/87bacd7c-805f-4055-a162-dc9d49660908)

**Comment by toprak** [comment]
LOOOOL they are totally same sorry for bother

**Comment by Metacor** [comment]
I know you already closed this since they both gave the same results, but I just wanted to say that there is already an option to do this; the ["Query"](https://i.imgur.com/bzaChNf.png) option added in [1.1.0](https://github.com/Metacor/nyaa-linker/releases/tag/v1.1.0) allows you to change the type of search query that is created.

Additionally the pipe **|** character is treated as an "or" when used with full quoted searches on nyaa, meaning it would match _either_ "x" **OR** "y", they don't _both_ need to be present. 

In some cases uploaders have different names that won't be exactly matched, typically titles with many odd characters or titles.separated.by.periods — although luckily that is very uncommon nowadays. 
In these rare cases, you can use the "fuzzy" option, which would search for just the main title (this is usually the romaji title, but depending on the website, it could be english), without the use of quotes, which I believe allows nyaa to match any combination of the words in the search, without having to be an exact match to your query.

**Comment by toprak** [comment]
@Metacor thank you for detailed clarification also thanks for this useful extension.
