### ISSUE TITLE
Searching sort options does not work other except Fuzzy 

### ISSUE THREAD

**Issue by toprak** [Metacor/nyaa-linker#6]
### Issue

https://anilist.co/anime/137877/Ganbare-Doukichan/
and try other all sort settings.	

### Expected Behavior

Give results

### Which Browser, and Browser Version are you using?

Edge Version 120.0.2210.91

### Which Extension Version are you using?

v1.2.0

**Comment by Metacor** [comment]
This seems to be a case of an odd naming choice by anilist.
I don't see how this could be fixed, because as I will detail below, this is the intended result given the title information. The only way to avoid this is to either use Fuzzy matching, or to use MyAnimeList. (Although to be clear, using anilist shouldn't be an issue for the vast majority of anime.)

The show is called "がんばれ同期ちゃん", which should be:
Romaji: Ganbare Douki-chan
English: Do Your Best, Douki-chan

For some reason, on anilist it is:
Romaji: Ganbare, Douki-chan (with a comma, which isn't typically used in romaji conversions)
English: GANBARE DOUKICHAN (which isn't english at all, and also doesn't include a hyphen for the honorific)

From what I can tell, most nyaa uploaders tend to use the [MyAnimeList](https://myanimelist.net/anime/49605/Ganbare_Douki-chan) naming schemes, so if you're not using MAL when searching, sometimes the names might not match.

"**Exact**" is searching for "Ganbare, Douki-chan"|"GANBARE DOUKICHAN", which is searching for something that matches EXACTLY one of those two terms, and since the listings on nyaa are for "Ganbare Douki-chan", neither search term will match it exactly, and thus will return no results.

"**Base**" only comes into play when there is stuff like parts/seasons in the title, where it will attempt to remove those and leave you with just the "base" series title ["Series Season 2" → "Series"], if there is no match for this, it just uses "Exact".

"**Default**" is just a combination of Base and Exact, so in this case, all 3 options are functionally identical. Additionally all options default to "Fuzzy" if there is only a single title or if the Japanese and English titles are the same; such as [Jujutsu Kaisen](https://anilist.co/anime/113415/Jujutsu-Kaisen), or funnily enough, the [Ganbare Douki-chan](https://myanimelist.net/anime/49605/Ganbare_Douki-chan) listing on MyAnimeList.

"**Fuzzy**" was made so you're able to search for non-exact titles, for cases specifically like this, where there is a weird naming decision (either by the database website, or by the nyaa uploaders).
